### ISSUE TITLE
libalpm v14 broke repo builder

### ISSUE THREAD

**Issue by kwankiu** [7Ji/arch_repo_builder#3]
~~It works on ALARM aarch64.~~ (no longer works)

But alpm fails on x86_64

with alpm 2.2.x : 
```
this version of alpm.rs does not support libalpm v14.0.0 only v13.x.x is supported
```

with latest alpm 3.x : 
```
   Compiling arch_repo_builder v0.2.0 (/home/user/Documents/GitHub/arb)
error[E0107]: struct takes 0 lifetime arguments but 1 lifetime argument was supplied
  --> src/depend/depends.rs:35:53
   |
35 | fn update_hash_from_pkg(hash: &mut xxh3::Xxh3, pkg: Package<'_>) {
   |                                                     ^^^^^^^---- help: remove these generics
   |                                                     |
   |                                                     expected 0 lifetime arguments
   |
note: struct defined here, with 0 lifetime parameters
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-3.0.5/src/package.rs:19:12
   |
19 | pub struct Package {
   |            ^^^^^^^

For more information about this error, try `rustc --explain E0107`.
error: could not compile `arch_repo_builder` (bin "arch_repo_builder") due to 1 previous error
```

**Comment by kwankiu** [comment]
@7Ji it looks like ALARM has also updated pacman to libalpm v14 now, the compiled binary no longer works on new or updated systems, and i guess in that case compiling it on aarch64 would likely result in same error with x86_64.

https://rebornos.discourse.group/t/libalpm-errors-while-updating/1242

**Comment by 7Ji** [comment]
Closed by https://github.com/7Ji/arb/commit/793b907006ca9be74c8677e4057f2fb78f7beb8f

**Comment by kwankiu** [comment]
@7Ji 
Works on x86_64 but not on aarch64 :
<img width="1306" alt="Screenshot 2024-03-17 at 10 57 57 PM" src="https://github.com/7Ji/arb/assets/29329276/a342dc20-893b-4f45-ba27-c7bd823f4b43">

**Comment by 7Ji** [comment]
Hmm it looks like alpm itself is broken on aarch64 currently, can you build alpm itself on aarch64 to test? If it's really broken then I'll need to open a PR to fix this upstream

**Comment by kwankiu** [comment]
https://github.com/Morganamilo/paru/issues/1085

**Comment by kwankiu** [comment]
#https://github.com/Morganamilo/paru/issues/1085

**Comment by kwankiu** [comment]
> Hmm it looks like alpm itself is broken on aarch64 currently, can you build alpm itself on aarch64 to test? If it's really broken then I'll need to open a PR to fix this upstream

Same error when building alpm.rs itself

**Comment by 7Ji** [comment]
A temporary workaround before upstream fixes their `ffi.rs`:

```
diff --git a/Cargo.toml b/Cargo.toml
index 32cacb3..71a9ac0 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -6,7 +6,7 @@ edition = "2021"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-alpm = "3.0"
+alpm = { version = "3.0", features = [ "generate" ] }
 blake2 = "0.10"
 crc = "3"
 env_logger = "0.10"

```

Remember to install `rust-bindgen` as dependency:
```
sudo pacman -S rust-bindgen
```

As this would introduce unneeded dependencies to x64 on which arb is not broken, I would not introduce the change in the short term.
