### ISSUE TITLE
Can we build (cross-compile) aarch64 kernel on x86_64?

### ISSUE THREAD

**Issue by kwankiu** [7Ji/arch_repo_builder#4]
I tried to build the packages on x86_64, I was able to build mesa successfully, but when I try to build any linux aarch64 kernel package, it fails.

ARB shows OS Error : Permission Denied
From the logs, it saids something like : 
```
make: No rules for “Image” 
```
Any idea?

[here's the config](https://github.com/kwankiu/acu/blob/pkgbuilds/arb/config.yaml)

**Comment by 7Ji** [comment]
You can't cross-compile anything with Arch's build system, which arb uses under the hood.  The build system just makes too many assumptions, most of them are basically expecting build host = build target. 

Even if you managed to build something aarch64-related on your x86_64 host, that would be, still, through and through, an x86_64 package, faked to be an aarch64 package. 

Some references:
https://github.com/w568w/alarm_repo/pull/1 (Check my reply)
https://github.com/Vexiona/archrepo/releases/tag/aarch64 (Check the content of usb2host package)
